management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

endpoints:
  beans:
    sensitive: false

demo:
  greeting:
    target:
      host: localhost
      port: 8081