management:
  server:
    ssl:
      enabled: true
      key-store: classpath:keystore.jks
      key-password: 123456
      key-alias: tomcat2
      key-store-password: 123456
      key-store-type: JKS
    port: 8443