management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    prometheus:
      enabled: true

demo:
  greeting:
    target:
#      host: localhost
#      port: 8081

spring:
  devtools:
    livereload:
      enabled: true
