management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  server:
    ssl:
      enabled: true
      key-store: classpath:keystore.jks
      key-password: 123456
      key-alias: tomcat
      key-store-password: 123456
    port: 8443

endpoints:
  beans:
    sensitive: false

demo:
  greeting:
    target:
#      host: localhost
#      port: 8081