management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    prometheus:
      enabled: true

demo:
  greeting:
    target:
#      host: localhost
#      port: 8081


spring:
  boot:
    admin:
      client:

        url: "http://localhost:8123"
#        enabled: true
        instance:
          health-url: "http://localhost:8080/actuator/health"

