version: "3"

services:
  demo:
    build:
      context: .
    image: demo:latest
    container_name: demo
    ports:
      - "8080:8080"
    environment:
      DEMO_GREETING_TARGET_HOST: echo
      DEMO_GREETING_TARGET_PORT: 3000
    networks:
      - demonetwork

  echo:
    image: kennship/http-echo:latest
    container_name: echo
    ports:
      - "8081:3000"
    networks:
      - demonetwork
  
  admin:
    image: aetas/spring-boot-admin-docker:1.4.1
    container_name: spring_boot_admin
    ports:
      - "8123:8090"
    networks: 
      - demonetwork

networks:
  demonetwork:
